version: "3.0"
services:
  pserver:
    container_name: pserver
    build: ./server
    tty: true
    cap_add:
    - NET_ADMIN
    networks:
      - z39_network
  pclient:
    container_name: pclient
    build: ./client
    tty: true
    cap_add:
    - NET_ADMIN
    privileged: true
    networks:
      - z39_network

networks:
  z39_network:
    external: true
