name: z39_zad2
services:
  pserver:
    container_name: z39_pserver
    build: ./server
    tty: true
    networks:
      - z39_network
  cclient:
    container_name: z39_cclient
    build: ./client
    tty: true
    networks:
      - z39_network

networks:
  z39_network:
    external: true
